language: java
env:
script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
- mvn clean test -Denv=test
deploy:
  provider: script
  script: mvn deploy -Denv=test -Dch.username="$CHUSERNAME" -Dch.password="$CHPASSWORD" -Dch.environment="$CHENVIRONMENT" -Dch.workerType="$CHWORKERTYPE" -Dch.region="$CHREGION" -Dch.businessGroup="$CHBUSINESSGROUP" -Daf.contextUrl="$AFCONTEXTURL" -Daf.username="$AFUSERNAME" -Daf.password="$AFPASSWORD" -Daf.repoKey="$AFREPOKEY" -Daf.snapshotRepoKey="$AFSNAPSHOTREPOKEY"
  on:
    branch: master
